# conda env create|update --file environment.yml
name: super-scaler
dependencies:
  - python
  - pip
  - pip:
      - '--editable=.'
      - jupyter
      - matplotlib
      - numpy
      - pandas
      - scipy
      - seaborn
      - sklearn
      - imageio
      - scikit-image
